### ISSUE TITLE
body font size differs

### ISSUE THREAD

**Issue by CaseyLeask** [CaseyLeask/developers.whatwg.org#2]
expected

``` css
body {
  font-size: 14px;
  line-height: 1.45em;
  font-family: "Droid Serif",Georgia,serif;
}
```

actual

``` css
body {
  font-size: 1.1em;
  line-height: 1.45em;
  font-family: "Droid Serif", Georgia, serif;
}
```
